// <auto-generated />
using System;
using FMInvestigacao.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FMInvestigacao.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220619200257_migration1")]
    partial class migration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FMInvestigacao.Model.Crime", b =>
                {
                    b.Property<int>("idCrime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCrime"), 1L, 1);

                    b.Property<int?>("VilaoidVilao")
                        .HasColumnType("int");

                    b.Property<DateTime?>("data")
                        .IsRequired()
                        .HasColumnType("DATETIME")
                        .HasColumnName("data");

                    b.Property<int>("duracao")
                        .HasColumnType("INT")
                        .HasColumnName("duracao");

                    b.Property<string>("local")
                        .HasMaxLength(45)
                        .HasColumnType("VARCHAR(45)")
                        .HasColumnName("local");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("VARCHAR(45)")
                        .HasColumnName("nome");

                    b.HasKey("idCrime");

                    b.HasIndex("VilaoidVilao");

                    b.ToTable("Crime", (string)null);
                });

            modelBuilder.Entity("FMInvestigacao.Model.Vilao", b =>
                {
                    b.Property<int>("idVilao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idVilao"), 1L, 1);

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("VARCHAR(45)")
                        .HasColumnName("nome");

                    b.Property<int>("numCrime")
                        .HasColumnType("INT")
                        .HasColumnName("numCrime");

                    b.HasKey("idVilao");

                    b.ToTable("Vilao", (string)null);
                });

            modelBuilder.Entity("FMInvestigacao.Model.Crime", b =>
                {
                    b.HasOne("FMInvestigacao.Model.Vilao", "Vilao")
                        .WithMany("Crimes")
                        .HasForeignKey("VilaoidVilao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Vilao_Crime");

                    b.Navigation("Vilao");
                });

            modelBuilder.Entity("FMInvestigacao.Model.Vilao", b =>
                {
                    b.Navigation("Crimes");
                });
#pragma warning restore 612, 618
        }
    }
}
